### ISSUE TITLE
Please add Sketchup 8, last official free for commercial use by google version of sketchup 

### ISSUE THREAD

**Issue by batchfileframework** [ad-si/awesome-3d-printing#25]
See this discussion

https://www.reddit.com/r/Sketchup/comments/or5xau/where_can_i_find_the_last_free_for_commercial_use/

and this one which has a link to the actual file

https://www.reddit.com/r/DataHoarder/comments/osfek8/hello_datahaoders_please_save_this_file_for_late/

Which leads to the backup on Internet Archive

https://archive.org/details/SketchUp-8.0.4811

Only thing you really need after that is the Export to STL extension which is still available in the extension warehouse (although I suspect Trimble will break V8 support if this old version ever gets too popular)

**Comment by ad-si** [comment]
Thanks for the suggestion, but people who know about Sketchup will find the link themselves and other people don't need to know about it as Sketchup 8 is quite old by now.
