### ISSUE TITLE
Please add the collection of all calibration and test print files

### ISSUE THREAD

**Issue by batchfileframework** [ad-si/awesome-3d-printing#26]
This list does not mention the benchy !

And there are many other test prints, these are often the first things you should print to test your machine.

To get started, here is a few test pieces I found around the internet

from https://all3dp.com/2/best-3d-printer-test-print-3d-models/

Benchy https://www.3dbenchy.com/download/

All-in-One https://www.thingiverse.com/thing:2656594/makes

Octagon https://www.thingiverse.com/thing:1363023

XYZ cube https://www.thingiverse.com/thing:1278865

Cali Cat https://www.thingiverse.com/thing:1545913

Phil A. Ment https://www.thingiverse.com/thing:2557603

Temperature Tower https://www.thingiverse.com/thing:2729076

Hollow Cube https://www.thingiverse.com/thing:16510

Open-Source Printer Evaluation https://github.com/kickstarter/kickstarter-autodesk-3d

PolyPearl Tower https://all3dp.com/2/best-3d-printer-test-print-3d-models/.

5-mm Steps https://www.thingiverse.com/thing:24238

Clearance Tolerance Test https://www.printables.com/model/116911-clearance-tolerance-test

Bed Leveling Calibration https://www.thingiverse.com/thing:34558

Slope Angle https://cults3d.com/en/3d-model/various/slopes-print-test

Shootout Collection https://www.thingiverse.com/thing:533472

Cali-Dragon https://www.thingiverse.com/thing:5401659

from https://all3dp.com/2/3d-printer-calibration-cube-the-best-models-how-to-use-them/

classic cube https://www.thingiverse.com/thing:1278865

Dimensional Accuracy pyramid https://www.youmagine.com/designs/make-2016-3d-printer-shootout-models

flow rate test cube https://www.prusaprinters.org/prints/81314-flow-calibration-cube

Hinged https://www.thingiverse.com/thing:4943713

hollow calibration cube https://www.thingiverse.com/thing:271736

Funky Hollow cube https://www.thingiverse.com/thing:16510

lego cube https://www.thingiverse.com/thing:4645349

Ghosting test cube https://www.thingiverse.com/thing:277394

Filament test cube https://www.thingiverse.com/thing:2166102

Lattice https://www.thingiverse.com/thing:1850320

Helix cube https://www.thingiverse.com/thing:5535095

Caliblock https://www.thingiverse.com/thing:1090268

Folding Box cube https://www.myminifactory.com/object/3d-print-folding-box-printer-calibration-cube-79492

from https://www.matterhackers.com/articles/top-ten-prints-to-calibrate-your-3d-printer

Overhang Test 

Bridging Test

Negative Space Test

Retraction Performance Test

Support Material Test

Full Bed Dimensional Accuracy Test

Z Wobble Test

Squareness Test

are all at https://www.thingiverse.com/thing:2755063

**Comment by ad-si** [comment]
Thanks for the suggestion! Good idea, but seems a little too much. Maybe you can pick the 10 best models and format them as a nice list? 😇

**Comment by ad-si** [comment]
I'll close this issue for the time being. Feel free to open a new one with a more focused selection.
