### ISSUE TITLE
Project Owner: Consider assigning maintainers

### ISSUE THREAD

**Issue by pbassut** [ad-si/awesome-3d-printing#27]
This shows up on the first result of google searches.
Don't let it die. At least assign some maintainers.

**Comment by cpritchett** [comment]
Giving this a bump.  Also happy to help maintain, there are a lot of great tools and projects that can be added here and this list needs to be added to the master Awesome repo. 

If there's no response from any of the maintainers, I'd be happy to maintain a fork with other collaborators.

**Comment by ad-si** [comment]
Just gave it a major rework!

The easiest way to keep it alive is to send PRs. If it's a good PR, I usually merge it in a few days. But thanks for you offers! I might come back to it if all my OSS repos are getting too much for me! 😅

Regarding the master Awesome repo:
I don't see the need anymore. Awesome Lists are quite known by now, and anyone who's searching for 3D printing will find this list.

**Comment by TheElbinho** [comment]
> If it's a good PR, I usually merge it in a few days.

Could not reproduce ;)

But seriously, this list is in quite some disarray. I wrote a push request that at least adresses all the open issues and cleans up the links in the "printer manufacturer" section, but there is still some work to be done. All relevant Slic3r forks are missing, and I haven't looked in detail at the model sites, but at least Thangs isn't there, too. I'm willing to add whatever I find, but it doesn't seem to make that much sense if the list isn't maintained

**Comment by ad-si** [comment]
Changing so many links in one PR makes it more work to review of course. 😅

All PRs are merged now and all issues are closed. So please keep em coming! =)
Thanks for your help!
